<x-layouts.premium title="Dashboard" subtitle="Übersicht über Lager, Reservierungen, Angebote und Verkauf.">
<x-slot name="head">
    <link rel="stylesheet" href="{{ asset('css/dashboard.css') }}">
</x-slot>
<section class="dashboard-kpi-grid">
@foreach ([['products.index','bi-box-seam','Inventar',$stats['products'],'Produkte'],['offers.index','bi-calendar-check','Reserviert',$stats['reservations'],'Aktive Reservierungen'],['offers.index','bi-receipt-cutoff','Vertrieb',$stats['offers'],'Angebote gesamt']] as $kpi)
<a href="{{ route($kpi[0]) }}" class="dashboard-kpi-card"><div class="dashboard-kpi-top"><span class="dashboard-kpi-icon"><i class="bi {{ $kpi[1] }}"></i></span><span class="dashboard-kpi-pill">{{ $kpi[2] }}</span></div><div class="dashboard-kpi-value">{{ $kpi[3] }}</div><div class="dashboard-kpi-label">{{ $kpi[4] }}</div></a>
@endforeach
</section>
<section class="dashboard-main-grid">
<div class="dashboard-panel"><div class="dashboard-panel-header"><div><h2>Verkaufsstatistik</h2><p>Auswertung erledigter Verkäufe nach verkaufter Menge.</p></div></div><div class="dashboard-ranking-grid">
@foreach ([['Top 10 meistverkauft',$topSellingProducts],['Top 10 am wenigsten verkauft',$leastSellingProducts]] as $ranking)
<div class="dashboard-ranking-block"><h3>{{ $ranking[0] }}</h3><div class="dashboard-ranking-list">@forelse($ranking[1] as $index=>$product)<a href="{{ route('products.show',$product->id) }}" class="dashboard-ranking-row"><span class="dashboard-rank">{{ $index+1 }}</span><span class="dashboard-product-name">{{ $product->name }}</span><strong>{{ number_format((float)$product->sold_quantity,2,',','.') }}</strong></a>@empty<div class="dashboard-empty">Noch keine Produkte vorhanden.</div>@endforelse</div></div>
@endforeach
</div></div>
<div class="dashboard-side-column">
<aside class="dashboard-panel dashboard-stock-panel"><div class="dashboard-panel-header"><div><h2>Lagerstatus</h2><p>Bestandslage und Warnungen.</p></div></div><div class="dashboard-stock-list"><a href="{{ route('warnings.index',['filter'=>'critical']) }}" class="dashboard-stock-item critical"><b>Kritisch</b><span>{{ $stats['critical'] }}</span></a><a href="{{ route('warnings.index',['filter'=>'low']) }}" class="dashboard-stock-item low"><b>Niedrig</b><span>{{ $stats['low'] }}</span></a><a href="{{ route('products.index') }}" class="dashboard-stock-item"><b>Produkte prüfen</b><span>{{ $stats['products'] }}</span></a></div><a href="{{ route('warnings.index') }}" class="dashboard-detail-link">Detailbericht öffnen →</a></aside>
<aside class="dashboard-panel dashboard-activities"><div class="dashboard-panel-header"><div><h2>Letzte Aktivitäten</h2><p>Die neuesten Systemaktionen.</p></div></div><div class="dashboard-compact-list">@forelse($latestActivities->take(4) as $activity)<div class="dashboard-compact-row"><span><b>{{ $activity->action }}</b><small>{{ $activity->user?->name ?? 'System' }}</small></span><time>{{ $activity->created_at?->format('d.m. H:i') }}</time></div>@empty<div class="dashboard-empty">Noch keine Aktivitäten vorhanden.</div>@endforelse</div><button type="button" class="dashboard-detail-link dashboard-button" data-dialog-open="activityModal" aria-controls="activityModal">Mehr anzeigen →</button></aside>
</div></section>
<dialog id="activityModal" class="dashboard-modal"><div class="dashboard-modal-card"><div class="dashboard-modal-header"><div><h2>Letzte Aktivitäten</h2><p>Datum/Uhrzeit, Benutzer, Aktion und betroffener Datensatz.</p></div><button type="button" data-dialog-close="activityModal" aria-label="Dialog schließen">×</button></div><div class="dashboard-modal-list">@forelse($latestActivities as $activity)<div class="dashboard-modal-row"><b>{{ $activity->created_at?->format('d.m.Y H:i') }}</b><span>{{ $activity->user?->name ?? 'System' }}</span><span>{{ $activity->action }}</span><span>{{ $activity->entity ?: '—' }} @if($activity->entity_id)#{{ $activity->entity_id }}@endif</span></div>@empty<div class="dashboard-empty">Noch keine Aktivitäten vorhanden.</div>@endforelse</div></div></dialog></x-layouts.premium>